"""Tests for btor2_reader.py — no network, no C++, no file I/O (except fixtures)."""
import hashlib
import textwrap
import tempfile
import os
import pytest

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from btor2_reader import (
    parse_btor2,
    hot_refs_near_bad,
    build_hot_variables,
    build_transition_sketch,
    _demangle_cbmc_name,
    _is_meaningful_symbol,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def make_btor2(content: str) -> str:
    """Write BTOR2 content to a temp file and return the path."""
    f = tempfile.NamedTemporaryFile(mode="w", suffix=".btor2", delete=False)
    f.write(textwrap.dedent(content))
    f.close()
    return f.name


# ---------------------------------------------------------------------------
# _is_meaningful_symbol
# ---------------------------------------------------------------------------

def test_meaningful_symbol_clean():
    assert _is_meaningful_symbol("wr_ptr") is True
    assert _is_meaningful_symbol("fifo.count") is True
    assert _is_meaningful_symbol("f_past_valid_gbl") is True


def test_meaningful_symbol_yosys_noise():
    assert _is_meaningful_symbol("$auto$clk2fflogic.cc:246:execute$4106") is False
    assert _is_meaningful_symbol("$techmap\\fifo.thing") is False
    assert _is_meaningful_symbol(None) is False
    assert _is_meaningful_symbol("") is False


def test_demangle_cbmc_state_names():
    assert _demangle_cbmc_name("!{$(in_main#0)<counter>}") == "counter"
    assert _demangle_cbmc_name("!{GLOBAL}") == "GLOBAL"
    assert _demangle_cbmc_name("!pc[3]") is None
    assert _demangle_cbmc_name("!{$(in_main#0)<counter>}.next") is None


# ---------------------------------------------------------------------------
# parse_btor2 — basic structure
# ---------------------------------------------------------------------------

SIMPLE_BTOR2 = """\
; BTOR description generated by Yosys for module myfifo.
1 sort bitvec 1
2 sort bitvec 8
3 input 1 i_clk
4 input 1 i_reset
5 input 1 i_wr
6 state 2 wr_ptr
7 state 2 rd_ptr
8 state 2 count
9 const 2 0
10 init 2 6 9
11 init 2 7 9
12 init 2 8 9
13 add 2 6 9
14 next 2 6 13
15 input 1 i_rd
16 sub 2 6 7
17 eq 1 8 16
18 not 1 17
19 bad 18
"""


@pytest.fixture()
def simple_path(tmp_path):
    p = tmp_path / "simple.btor2"
    p.write_text(textwrap.dedent(SIMPLE_BTOR2))
    return str(p)


def test_parse_module_name(simple_path):
    info = parse_btor2(simple_path)
    assert info.module_name == "myfifo"


def test_parse_inputs(simple_path):
    info = parse_btor2(simple_path)
    symbols = [iv.symbol for iv in info.inputs]
    assert "i_clk" in symbols
    assert "i_reset" in symbols
    assert "i_wr" in symbols
    assert "i_rd" in symbols


def test_parse_states(simple_path):
    info = parse_btor2(simple_path)
    refs = [sv.ref for sv in info.states]
    assert "state6" in refs
    assert "state7" in refs
    assert "state8" in refs


def test_state_symbols(simple_path):
    info = parse_btor2(simple_path)
    by_ref = {sv.ref: sv for sv in info.states}
    assert by_ref["state6"].symbol == "wr_ptr"
    assert by_ref["state7"].symbol == "rd_ptr"
    assert by_ref["state8"].symbol == "count"


def test_state_width(simple_path):
    info = parse_btor2(simple_path)
    by_ref = {sv.ref: sv for sv in info.states}
    assert by_ref["state6"].width == 8
    assert by_ref["state8"].width == 8


def test_state_init(simple_path):
    info = parse_btor2(simple_path)
    by_ref = {sv.ref: sv for sv in info.states}
    assert by_ref["state6"].init_value == "0"
    assert by_ref["state8"].init_value == "0"


def test_bad_lineno(simple_path):
    info = parse_btor2(simple_path)
    # bad 18 → bad_lineno = 18 (the expr line)
    assert info.bad_lineno == 18
    assert info.bad_count == 1
    assert info.node_count == 19
    assert info.line_count == 20
    assert len(info.text_sha256) == 64


def test_text_sha256_hashes_exact_file_bytes(tmp_path):
    raw = b"1 sort bitvec 1\r\n2 state 1 x\r\n"
    path = tmp_path / "crlf.btor2"
    path.write_bytes(raw)
    info = parse_btor2(str(path))
    assert info.text_sha256 == hashlib.sha256(raw).hexdigest()


def test_parse_array_state_metadata(tmp_path):
    path = tmp_path / "array.btor2"
    path.write_text(textwrap.dedent("""\
    1 sort bitvec 8
    2 sort bitvec 16
    3 sort array 1 2
    4 state 3 memory
    5 state 2 scalar
    """))
    info = parse_btor2(str(path))
    by_ref = {state.ref: state for state in info.states}
    assert by_ref["state4"].is_array is True
    assert by_ref["state4"].width == 0
    assert by_ref["state4"].data_bits == 16
    assert by_ref["state5"].is_array is False
    assert by_ref["state5"].width == 16
    assert info.array_sort_count == 1


def test_init_constants_are_normalized_to_unsigned_decimal(tmp_path):
    path = tmp_path / "constants.btor2"
    path.write_text(textwrap.dedent("""\
    1 sort bitvec 8
    2 const 1 00000010
    3 constd 1 10
    4 consth 1 10
    5 ones 1
    6 state 1 binary_two
    7 state 1 decimal_ten
    8 state 1 hex_sixteen
    9 state 1 all_ones
    10 init 1 6 2
    11 init 1 7 3
    12 init 1 8 4
    13 init 1 9 5
    """))
    info = parse_btor2(str(path))
    by_ref = {state.ref: state for state in info.states}
    assert by_ref["state6"].init_value == "2"
    assert by_ref["state7"].init_value == "10"
    assert by_ref["state8"].init_value == "16"
    assert by_ref["state9"].init_value == "255"


# ---------------------------------------------------------------------------
# hot_refs_near_bad
# ---------------------------------------------------------------------------

def test_hot_refs_basic(simple_path):
    info = parse_btor2(simple_path)
    # bad(line 19) expr=18: not→17→eq(8,16)→sub(6,7)
    # depth=3 reaches state8 (via eq's direct arg); depth=4 reaches state6,state7
    refs3 = hot_refs_near_bad(info, depth=3)
    assert "state8" in refs3          # count is 3 hops from bad
    refs4 = hot_refs_near_bad(info, depth=4)
    assert "state6" in refs4 or "state7" in refs4   # wr_ptr/rd_ptr are 4 hops


def test_hot_refs_empty_when_no_bad():
    import io
    content = "1 sort bitvec 1\n2 state 1 x\n"
    f = tempfile.NamedTemporaryFile(mode="w", suffix=".btor2", delete=False)
    f.write(content)
    f.close()
    info = parse_btor2(f.name)
    os.unlink(f.name)
    refs = hot_refs_near_bad(info, depth=3)
    assert refs == []


# ---------------------------------------------------------------------------
# build_hot_variables
# ---------------------------------------------------------------------------

def test_build_hot_variables(simple_path):
    info = parse_btor2(simple_path)
    refs = ["state6", "state7"]
    hvars = build_hot_variables(info, refs)
    assert len(hvars) == 2
    by_ref = {h["ref"]: h for h in hvars}
    assert by_ref["state6"]["width"] == 8
    assert by_ref["state6"]["verilog"] == "wr_ptr"
    assert by_ref["state7"]["verilog"] == "rd_ptr"
    assert "init" in by_ref["state6"]


def test_build_hot_variables_no_symbol():
    """States without meaningful symbols should not have 'verilog' key."""
    content = textwrap.dedent("""\
    ; BTOR description for module foo.
    1 sort bitvec 4
    2 state 1 $auto$clk:42
    """)
    f = tempfile.NamedTemporaryFile(mode="w", suffix=".btor2", delete=False)
    f.write(content)
    f.close()
    info = parse_btor2(f.name)
    os.unlink(f.name)
    hvars = build_hot_variables(info, ["state2"])
    assert "verilog" not in hvars[0]


# ---------------------------------------------------------------------------
# build_transition_sketch
# ---------------------------------------------------------------------------

def test_transition_sketch(simple_path):
    info = parse_btor2(simple_path)
    sketch = build_transition_sketch(info, ["state6"])
    assert len(sketch) == 1
    assert "wr_ptr" in sketch[0] or "state6" in sketch[0]


def test_transition_sketch_no_next():
    """States without next should produce empty sketch."""
    content = textwrap.dedent("""\
    ; BTOR description for module bar.
    1 sort bitvec 4
    2 state 1 x
    """)
    f = tempfile.NamedTemporaryFile(mode="w", suffix=".btor2", delete=False)
    f.write(content)
    f.close()
    info = parse_btor2(f.name)
    os.unlink(f.name)
    sketch = build_transition_sketch(info, ["state2"])
    assert sketch == []


# ---------------------------------------------------------------------------
# Realistic p040 BTOR2 snippet
# ---------------------------------------------------------------------------

P040_SNIPPET = """\
; BTOR description generated by Yosys 0.9+899 for module imgfifo.
1 sort bitvec 24
2 input 1 i_baseaddr
3 sort bitvec 1
4 input 3 i_clk
5 sort bitvec 12
6 input 5 i_linewords
7 input 3 i_newframe
8 sort bitvec 11
9 input 8 i_nlines
10 input 3 i_pixclk
11 input 3 i_rd
12 input 3 i_reset
13 sort bitvec 32
19 state 3 $auto$clk2fflogic.cc:246:execute$4106
20 init 3 19 18
21 state 3 fifo.f_past_valid_gbl
22 init 3 21 18
18 const 3 0
193 state 127 f_clk_count
194 const 127 0
195 init 127 193 194
199 state 127 f_pclk_count
200 const 127 0
201 init 127 199 200
300 eq 3 193 199
301 not 3 300
302 bad 301
"""


@pytest.fixture()
def p040_path(tmp_path):
    p = tmp_path / "p040_snippet.btor2"
    p.write_text(textwrap.dedent(P040_SNIPPET))
    return str(p)


def test_p040_module_name(p040_path):
    info = parse_btor2(p040_path)
    assert info.module_name == "imgfifo"


def test_p040_inputs(p040_path):
    info = parse_btor2(p040_path)
    syms = {iv.symbol for iv in info.inputs}
    assert "i_clk" in syms
    assert "i_rd" in syms
    assert "i_newframe" in syms


def test_p040_states_clean_vs_noisy(p040_path):
    info = parse_btor2(p040_path)
    by_ref = {sv.ref: sv for sv in info.states}
    # Noisy symbol → None
    assert by_ref["state19"].symbol is None
    # Clean symbol → present
    assert by_ref["state21"].symbol == "fifo.f_past_valid_gbl"
    assert by_ref["state193"].symbol == "f_clk_count"


def test_p040_hot_refs(p040_path):
    info = parse_btor2(p040_path)
    refs = hot_refs_near_bad(info, depth=3)
    # bad→301 not→300 eq→193,199 → state193, state199
    assert "state193" in refs
    assert "state199" in refs
